---
- name: A playbook that will call multiple roles
  hosts: all

  # Gather facts needed to retrieve hostname
  gather_facts: true

  vars:
    nexthop: somethingiwilloverride.example.org
    nexthop_port: 2525
    searchdomain: mysubdomain.example.org
    resolver1: 8.8.8.8
    resolver2: 8.8.4.4

  tasks:
  - name: call mxout role
    ansible.builtin.include_role:
      name: mxout

  - name: call resolver role
    ansible.builtin.include_role:
      name: resolvconf
